### ISSUE TITLE
File Location?

### ISSUE THREAD

**Issue by You4eea** [hachesilva/Comment-Snippets#11]
I am using sublime text 3 on windows 7 pro... Question is where are the files stored?

**Comment by hachesilva** [comment]
Hey!

You can check your Sublime packages location going to "Preferences" -> "Browse packages...", it will open an Explorer window with the default path for Sublime packages, this path is usually %AppData%/Roaming/Sublime Text 3/Packages/. However, usually not all packages are there, some of them are in a folder called Installed Packages with a ".sublime-package" extension.
