### ISSUE TITLE
Modify Comments?

### ISSUE THREAD

**Issue by You4eea** [hachesilva/Comment-Snippets#13]
I am so sorry, after I re-read my question I realized how vague it was.. sincerest apologies.

If I may try to better explain my question.

Is there a way to change the comment tag styles?
For example this comment block
/_=====  End of Section comment block  ======_/

Is there a way to change the way it looks, for example, if I wanted to add more stars(_):
/_******_=  End of Section comment block  =**_****/

Again, sorry for the vague earlier attempt.

Thanks

**Comment by hachesilva** [comment]
Hi @You4eea. Sorry for the very late response.

Don't worry, adding details to your question is just fine...

So, to edit the plugin and add more stars or do any kind of changes just follow my previous steps (go to Preferences -> Browse Packages, move up one folder and access Installed Packages folder). You'll find a package called "Comment-Snippets.sublime-package", that is just a zip file renamed to use a .sublime-package extension, so copy it to another location (Desktop maybe), rename it back to Comment-Snippets.zip and decompress it. Then, you'll get a zip folder with all snippets inside. Open the ones yo want to edit with Sublime Text or any other text editor and make your changes.

If you think your changes are relevant to other developers or you are fixing any bug on the snippets, please feel free to create a pull request with your changes. If you don't want/need to share or the changes are relevant to just you then go ahead and zip the edited snippets, rename the zip file using the sublime-package extension, move it to the Installed Packages folder and restart Sublime.

That's it. Please feel free to ask any additional question if you have it.

Happy hacking :)
