### ISSUE TITLE
feature_request: comments with scope

### ISSUE THREAD

**Issue by Dovermore** [hachesilva/Comment-Snippets#19]
All the snippets don't have a scope setting. It's quite annoying that one has to select the correct scope choice each time. Can we have the scope settings added?

**Comment by hachesilva** [comment]
Hey Dovermore.

I initially decided to create snippets without scopes so they could work on almost any language.

Can you please elaborate on why do you need to choose scope to use them? I haven't experienced this annoyance.

**Comment by Dovermore** [comment]
It's not a serious problem. 

Since you introduced `python`, `HTML` and `C` like comments in all together, when I tried to add say python comments, the dropdown is simply cluttered with different styles. I'm aware that the fuzzy search feature can help quickly select the correct scope, but still quite often choose the wrong one.

Also, I've edited the snippets on my machine adding scopes to the snippets. You can close the discussion safely.
