### ISSUE TITLE
if block comment style shuldn't have different structure

### ISSUE THREAD

**Issue by cachaito** [hachesilva/Comment-Snippets#5]
Hi! Did You considered more common structure of block-comment as:
```
/**
 * @name
 * @desc
 */
```
instead 
```
/**
*
* Block comment
*
**/
```

Best regards!

**Comment by hachesilva** [comment]
Hi.

"More common" to what? I mean, where is it commonly used as suggested? DocBlock, Doxygen?

Please show me any reference so I can compare and decide what block-comment style should I use.

**Comment by cachaito** [comment]
The first syntax is from: [JSDoc](http://usejsdoc.org/about-getting-started.html) Sorry if I didn't explain it enough clearly. For my environment is it is very common comment syntax.

**Comment by hachesilva** [comment]
DocBlock, JSDoc and Doxygen use the suggested style, so I'll be updating the repo very soon. If you can help making the change and requesting a pull that'd be great.

**Comment by cachaito** [comment]
Hi Hernán! I was wrong to prompt You about changing style of Your block comment. Recently I've found [Dockblckr](https://github.com/spadgos/sublime-jsdocs) which handles JSDoc perfectly. There's no reason to copy this style in Your snippets.

Best regards!
