### ISSUE TITLE
Auto-complete not working

### ISSUE THREAD

**Issue by jacobgraf** [hachesilva/Comment-Snippets#6]
How do you get your autocomplete to fire when typing `comm-`?

**Comment by hachesilva** [comment]
Hi @jacobgraf 

If you are using a syntax such as CSS, PHP, Javascript or similar, it should just open a list of suggestions for you to autocomplete. If the suggestion list doesn´t show up or you are using another syntax, using Ctrl+Space will do the trick.

Please let me know if that answers your question.
