### ISSUE TITLE
Todo Comment Syntax highlighting issues

### ISSUE THREAD

**Issue by nicdford** [hachesilva/Comment-Snippets#7]
For some reason sublime doesn't like /** to open the comment tag. It weirdly highlights everything between the beginning and closing tags:

![image](https://cloud.githubusercontent.com/assets/7292444/9615318/3d584c80-50ac-11e5-98b5-5fc2f4c2154b.png)

Remove the second * on the opening tag fixes the issue or adding * to each line within the comment.

**Comment by hachesilva** [comment]
It may happen if you use some default or contriibuted color schemes not supporting that kind of comments. So, it is not because Sublime doesn´t like them, the fault is on color schemes.

Using a new color scheme should solve it.
